# Generated by Django 3.1.3 on 2020-11-23 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='addtask',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
