# Generated by Django 3.1.3 on 2020-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtask', '0002_auto_20201123_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='datetime',
        ),
        migrations.AddField(
            model_name='addtask',
            name='date',
            field=models.DateField(blank=True, default='2020-11-24'),
        ),
        migrations.AddField(
            model_name='addtask',
            name='time',
            field=models.TimeField(blank=True, default='00:14:12'),
        ),
    ]
