# Generated by Django 3.1.3 on 2020-11-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtask', '0003_auto_20201124_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='time',
            field=models.TimeField(blank=True, default='15:07:46'),
        ),
    ]
