# Generated by Django 3.1.3 on 2020-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtask', '0004_auto_20201124_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='time',
            field=models.TimeField(blank=True, default='15:40:59'),
        ),
    ]
