# Generated by Django 3.1.5 on 2021-01-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtask', '0009_auto_20201203_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='date',
            field=models.DateField(blank=True, default='2021-01-23'),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='time',
            field=models.TimeField(blank=True, default='00:12:28'),
        ),
    ]
